### ISSUE TITLE
Style-loader fails when context.env === test

### ISSUE THREAD

**Issue by yifanwangsh** [DocSpring/craco-less#16]
https://github.com/DocSpring/craco-less/blob/2e6aea9fb9a6558b3346b6e944b0bbeb694f770d/lib/craco-less.js#L64

I am trying to boot up my create-react-app with craco in a testing environment (puppeteer). It fails because the context environment is test instead of development, and style-loader cannot be used. 

```javascript
node_modules\@craco\craco\lib\plugin-utils.js:29
    throw new Error(
    ^

Error: Found an unhandled loader in the test webpack config: node_modules\style-loader\index.js

at throwUnexpectedConfigError (node_modules\@craco\craco\lib\plugin-utils.js:29:11)
    at throwError (node_modules\craco-less\lib\craco-less.js:14:5)
    at loaders.forEach.ruleOrLoader (node_modules\craco-less\lib\craco-less.js:113:7)
    at Array.forEach (<anonymous>)
    at Object.overrideWebpackConfig (node_modules\craco-less\lib\craco-less.js:53:11)
    at Object.overrideWebpackConfig (node_modules\craco-antd\lib\craco-antd.js:63:26)
```

**Comment by yifanwangsh** [comment]
#17
