### ISSUE TITLE
CRA 3.1.0 - webpack unknown rule 

### ISSUE THREAD

**Issue by starsolaris** [DocSpring/craco-less#18]
After upgrading CRA to 3.1.0, build stop with next exception:

g:\source\simpleui\src\node_modules\@craco\craco\lib\plugin-utils.js:29
    throw new Error(
    ^

Error: Found an unhandled loader in the development webpack config: g:\source\simpleui\src\node_modules\resolve-url-loader\index.js

This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

If that doesn't work, craco-less needs to be fixed to support the latest version.
Please check to see if there's already an issue in the FormAPI/craco-less repo:

   * https://github.com/FormAPI/craco-less/issues?q=is%3Aissue+webpack+unknown+rule

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue+webpack+unknown+rule
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue+webpack+unknown+rule

    at throwUnexpectedConfigError (g:\source\simpleui\src\node_modules\@craco\craco\lib\plugin-utils.js:29:11)
    at throwError (g:\source\simpleui\src\node_modules\craco-less\lib\craco-less.js:14:5)
    at loaders.forEach.ruleOrLoader (g:\source\simpleui\src\node_modules\craco-less\lib\craco-less.js:112:7)
    at Array.forEach (<anonymous>)
    at Object.overrideWebpackConfig (g:\source\simpleui\src\node_modules\craco-less\lib\craco-less.js:52:11)
    at overrideWebpack (g:\source\simpleui\src\node_modules\@craco\craco\lib\features\plugins.js:40:40)
    at cracoConfig.plugins.forEach.x (g:\source\simpleui\src\node_modules\@craco\craco\lib\features\plugins.js:60:29)
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (g:\source\simpleui\src\node_modules\@craco\craco\lib\features\plugins.js:59:29)
    at overrideWebpack (g:\source\simpleui\src\node_modules\@craco\craco\lib\features\webpack.js:65:21)
    at Object.<anonymous> (g:\source\simpleui\src\node_modules\@craco\craco\scripts\start.js:21:1)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "start" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by Haqverdi** [comment]
same

**Comment by Moskvyak** [comment]
same thing, it's working with CPA 3.0.0 but not working with 3.1.0+

**Comment by renleiabc** [comment]
![image](https://user-images.githubusercontent.com/24283195/82724283-731f8980-9d07-11ea-975e-ec6887e8f642.png)
