### ISSUE TITLE
Getting error that craco-less needs to be updated

### ISSUE THREAD

**Issue by jest-games** [DocSpring/craco-less#59]
When I run my application I get the following error. I have tried updating my version of craco-less and making sure my REACT_APP_ENV variable is set correctly. Does the current version need to be updated?

```
yarn run v1.22.5
$ craco start
(node:27606) UnhandledPromiseRejectionWarning: Error: Found an unhandled loader in the local webpack config: /home/conrardy/src/jest-games/client/node_modules/style-loader/dist/cjs.js

This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

If that doesn't work, craco-less needs to be fixed to support the latest version.
Please check to see if there's already an issue in the DocSpring/craco-less repo:

   * https://github.com/DocSpring/craco-less/issues?q=is%3Aissue+webpack+unknown+rule

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue+webpack+unknown+rule
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue+webpack+unknown+rule

    at throwUnexpectedConfigError (/home/conrardy/src/jest-games/client/node_modules/@craco/craco/lib/plugin-utils.js:29:11)
    at throwError (/home/conrardy/src/jest-games/client/node_modules/craco-less/lib/craco-less.js:14:5)
    at loaders.forEach.ruleOrLoader (/home/conrardy/src/jest-games/client/node_modules/craco-less/lib/craco-less.js:119:7)
    at Array.forEach (<anonymous>)
    at Object.overrideWebpackConfig (/home/conrardy/src/jest-games/client/node_modules/craco-less/lib/craco-less.js:51:11)
    at overrideWebpack (/home/conrardy/src/jest-games/client/node_modules/@craco/craco/lib/features/plugins.js:42:40)
    at cracoConfig.plugins.forEach.x (/home/conrardy/src/jest-games/client/node_modules/@craco/craco/lib/features/plugins.js:64:29)
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (/home/conrardy/src/jest-games/client/node_modules/@craco/craco/lib/features/plugins.js:63:29)
    at mergeWebpackConfig (/home/conrardy/src/jest-games/client/node_modules/@craco/craco/lib/features/webpack/merge-webpack-config.js:110:30)
(node:27606) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27606) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 5.02s.
```

**Comment by jest-games** [comment]
Closing this issue, I changed my REACT_APP_ENV to development and it was not working however changing NODE_ENV to development seemed to work.

**Comment by A-GG** [comment]
I got the same issue when run build task at jenkins.

```
> craco build

(node:127274) UnhandledPromiseRejectionWarning: Error: Found an unhandled loader in the production webpack config: /var/lib/jenkins/workspace/xxxx/node_modules/_mini-css-extract-plugin@0.11.3@mini-css-extract-plugin/dist/loader.js

This error probably occurred because you updated react-scripts or craco. Please try updating craco-less to the latest version:

   $ yarn upgrade craco-less

Or:

   $ npm update craco-less

If that doesn't work, craco-less needs to be fixed to support the latest version.
Please check to see if there's already an issue in the DocSpring/craco-less repo:

   * https://github.com/DocSpring/craco-less/issues?q=is%3Aissue+webpack+unknown+rule

If not, please open an issue and we'll take a look. (Or you can send a PR!)

You might also want to look for related issues in the craco and create-react-app repos:

   * https://github.com/sharegate/craco/issues?q=is%3Aissue+webpack+unknown+rule
   * https://github.com/facebook/create-react-app/issues?q=is%3Aissue+webpack+unknown+rule

    at throwUnexpectedConfigError (/var/lib/jenkins/workspace/*****/node_modules/_@craco_craco@6.1.1@@craco/craco/lib/plugin-utils.js:29:11)
    at throwError (/var/lib/jenkins/workspace/xxxxx/node_modules/_craco-less@1.17.1@craco-less/lib/craco-less.js:14:5)
    at /var/lib/jenkins/workspace/xxxxx/node_modules/_craco-less@1.17.1@craco-less/lib/craco-less.js:119:7
    at Array.forEach (<anonymous>)
    at Object.overrideWebpackConfig (/var/lib/jenkins/workspace/*****/node_modules/_craco-less@1.17.1@craco-less/lib/craco-less.js:51:11)
    at overrideWebpack (/var/lib/jenkins/workspace/*****node_modules/_@craco_craco@6.1.1@@craco/craco/lib/features/plugins.js:42:40)
    at /var/lib/jenkins/workspace/*****/node_modules/_@craco_craco@6.1.1@@craco/craco/lib/features/plugins.js:64:29
    at Array.forEach (<anonymous>)
    at applyWebpackConfigPlugins (/var/lib/jenkins/workspace/*****/node_modules/_@craco_craco@6.1.1@@craco/craco/lib/features/plugins.js:63:29)
    at mergeWebpackConfig (/var/lib/jenkins/workspace/*****/node_modules/_@craco_craco@6.1.1@@craco/craco/lib/features/webpack/merge-webpack-config.js:110:30)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:127274) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:127274) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by SunnyXiao** [comment]
any changes？ i have the same issues

**Comment by bihongbin3027** [comment]
i have the same issues

**Comment by flacoman91** [comment]
> i have the same issues

Check your environment variables.  NODE_ENV has to be set to `production` or `development` or you will get the error.
`export NODE_ENV=production`
or
`export NODE_ENV=development`

Alternatively, you can just run the command `unset NODE_ENV`  to clear out the value before running the command.

**Comment by DYDY233** [comment]
try to uninstall node_modules, then npm install -legacy-peer-deps.

**Comment by hhuabin** [comment]
i have the same issues，so, how to solve it?

**Comment by zhuzeyu22** [comment]
i have the same issues，so, how to solve it?

**Comment by zulqarnain-empg** [comment]
how to solve this issue?

**Comment by syukranDev** [comment]
works fine when set NODE_ENV=development
